os:
  - linux
  - osx

language: node_js
node_js:
  - 4
  - 5
  - 6
  - 7

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install zmq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir ldlocal; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export LDHACK=`pwd`/ldlocal; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export LDFLAGS=-L$LDHACK/lib; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CFLAGS=-I$LDHACK/include; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export LD_RUN_PATH=$LDHACK/lib; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export LD_LIBRARY_PATH=$LDHACK/lib; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PKG_CONFIG_PATH=$LDHACK/lib/pkgconfig; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/zeromq/$ZMQ_REPO/releases/download/v$ZMQ/zeromq-$ZMQ.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar xzvf zeromq-$ZMQ.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd zeromq-$ZMQ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./autogen.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure --prefix=$LDHACK; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make -j; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make install; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ..; fi

script:
  - travis_retry npm run report:coveralls

env:
  global:
    - NODE_ENV=development
    - ZMQ=4.1.6
    - ZMQ_REPO=zeromq4-1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
